
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-30T07:47:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c36c72678040a3b7deb3589c8eb37a55337a8251",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
