
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T22:24:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ab1449eaa78c1ec07a5974eac15003bb31ce298",
 "version": "1.9.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
