# Generated by Django 3.2.13 on 2022-06-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_auto_20200803_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_state',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
