
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T13:22:34+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "4848211867432f61ef25389bb270adfd2e7f339d",
 "version": "v3.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
