
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T16:42:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "75ccb396590bb5ea3e3aca30d4b1ea8f4705f46b",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
