
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T09:46:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "933526a6370e7e70cf52c7c7ee71fba1d3ab4ba7",
 "version": "0.1.0a78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
