VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('28')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 0
MINOR_VERSION = 19
PATCH_VERSION = 202210281200
version_date = '2022/10/28 12:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
