
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T10:06:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0a98fdc03a4dbc19c666f605753df8d00363650",
 "version": "0.1.3.post0.dev115"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
