
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-29T09:34:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b52c0e6bba2713c056ce6d81487eb79c7a7c152f",
 "version": "0.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
