
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T16:57:27+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c006478e8bf7efae7272bf86827180681d096f0",
 "version": "0.1.2rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
