
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T08:40:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a10b51f65179a99828f4da6700beeb035d644620",
 "version": "v1.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
