
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T16:50:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e5a19b246aa684d2bedfb4673960d895d81dd24",
 "version": "v22.12.00a221102"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
