
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T12:34:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9702cbc8953f36deafbd6be629c4ac8818f78e29",
 "version": "22.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
