# Generated by Django 3.2.13 on 2022-06-27 19:15

import django.core.serializers.json
from django.db import migrations, models
import funkwhale_api.music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0054_alter_uploadversion_mimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='import_details',
            field=models.JSONField(blank=True, default=funkwhale_api.music.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='upload',
            name='import_metadata',
            field=models.JSONField(blank=True, default=funkwhale_api.music.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='upload',
            name='metadata',
            field=models.JSONField(blank=True, default=funkwhale_api.music.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
    ]
