# Generated by Django 3.2.14 on 2022-07-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0055_auto_20220627_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='content_category',
            field=models.CharField(choices=[('music', 'music'), ('podcast', 'podcast'), ('other', 'other')], db_index=True, default='music', max_length=30),
        ),
    ]
