
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T11:23:23+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "c719e23937e3f9a620d38c54bfdc4bfe5fa05e88",
 "version": "0.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
