
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T12:47:30+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "72d04d4c747bee076de31eac3d99ce478ba7480e",
 "version": "v3.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
