
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T18:29:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "292350f4cc06ca274a15b5e7101e56f25b0093a9",
 "version": "v0.25.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
