# Generated by Django 3.2.13 on 2022-06-27 19:15

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200701_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='is_applied',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='payload',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='previous_state',
            field=models.JSONField(default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='pluginconfiguration',
            name='conf',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
