
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-29T13:13:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a28d6babe6d197bfd3725f0b207065789fc0a9a",
 "version": "2022.10.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
