
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T15:20:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b7f79127eae1757a7c2882e64bf474f0bcd5c5b",
 "version": "v1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
