
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T10:48:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "51e48ff11780b9bc1439c33351cb6cd1d1487403",
 "version": "1.0.0b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
