
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T11:54:45+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "908024bdf1b2f9714213d7455c43cdac8fb3ceb2",
 "version": "0.17.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
