
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T13:46:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5355ce91e2ab9807aa7d257375b95e47d52fbcd1",
 "version": "1.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
