# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracdap/config/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btracdap/config/common.proto\x12\x0etracdap.config\"u\n\x0b_ConfigFile\x12\x37\n\x06\x63onfig\x18\x01 \x03(\x0b\x32\'.tracdap.config._ConfigFile.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*H\n\x0c\x43onfigFormat\x12\x19\n\x15\x43ONFIG_FORMAT_NOT_SET\x10\x00\x12\x08\n\x04YAML\x10\x01\x12\x08\n\x04JSON\x10\x02\x12\t\n\x05PROTO\x10\x03\x42\x1c\n\x18org.finos.tracdap.configP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracdap.config.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.finos.tracdap.configP\001'
  __CONFIGFILE_CONFIGENTRY._options = None
  __CONFIGFILE_CONFIGENTRY._serialized_options = b'8\001'
  _CONFIGFORMAT._serialized_start=166
  _CONFIGFORMAT._serialized_end=238
  __CONFIGFILE._serialized_start=47
  __CONFIGFILE._serialized_end=164
  __CONFIGFILE_CONFIGENTRY._serialized_start=119
  __CONFIGFILE_CONFIGENTRY._serialized_end=164
# @@protoc_insertion_point(module_scope)
