
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-30T11:17:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "665b1b5215517759977ca44194ba5747d6fdde92",
 "version": "0.10.3a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
