
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T16:34:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9eaa2322bb314620ce8ac0cd5da53b2303cd5087",
 "version": "v1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
