
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-30T02:53:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "966860a325649d0b4761a746b47803ad447db708",
 "version": "0.5.dev2244"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
