import pandas as pd
from _typeshed import Incomplete
from solas_disparity import const as const
from typing import Any, Callable, Dict, Union

AUTO_FORMATTERS: Incomplete

def autoformatter() -> Dict[str, Callable]: ...

NA_REP: str

def is_in_ipynb() -> bool: ...
def df_to_html_defaults(obj: pd.DataFrame, is_notebook: bool = ...) -> dict: ...
def show(obj: Union[pd.DataFrame, Any], auto_format: bool = ...) -> None: ...
def init_notebook() -> None: ...
