
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T20:36:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce1cacf9813802a66a8a92405127af37d0004045",
 "version": "0.2.39.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
