
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-29T17:32:08-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "e8cd10fb32d3d112b2dedef5a711917a0e0e71f2",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
