
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T17:37:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "242b883ccfb833d22aae0c937bb7cf82634754c1",
 "version": "v0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
