
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T12:43:33+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "23ddcb4a87c451dd705e9856d2e98fcd2faa4b5b",
 "version": "v3.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
