
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-21T12:17:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ce6b87b1f9acda78e21fa4ed095b8cc4964ff4a",
 "version": "v0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
