
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T16:17:46-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6bde5246fdc313451971c4094d5ec39a54759d7e",
 "version": "6.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
