
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T18:32:27+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "9656178bef1007146bf5cdc47de2bd683caab82e",
 "version": "v3.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
