
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T08:47:30+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "59abe547757754af1ced2bec1f13f17b7b09cd0f",
 "version": "0.29.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
