
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T09:06:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9d6d84b286300069d7e887728c46de1f9e1ac83",
 "version": "1.6.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
