
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T10:09:32-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "66886677632910fe81db0b0058dcd66020a99454",
 "version": "1.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
