from .cowley2022mapping_courtship_audiointerface import Cowley2022MappingCourtshipAudioInterface
from .cowley2022mapping_courtship_behaviorinterface import Cowley2022MappingCourtshipBehaviorInterface
from .cowley2022mapping_imaging_behaviorinterface import Cowley2022MappingImagingBehaviorInterface
from .cowley2022mapping_imaging_imaginginterface import Cowley2022MappingImagingMultipleInterface
from .cowley2022mapping_imaging_segmentationinterface import Colwey2022MappingSegmentationInterface
from .cowley2022mapping_imaging_stimuliinterface import Cowley2022MappingImagingStimuliInterface
