
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T11:28:10+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8556fdad850a19ba6eb9b2a46b2b5c839f6ccbf3",
 "version": "3.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
