
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T19:40:19-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "94bbdcdc9c1b59c3c049efb0b56c7fb87bb6a0d6",
 "version": "0.0.128"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
