
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T21:45:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e587d709955940d32ca2f931e41b9666ef84a016",
 "version": "0.5.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
