
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T09:26:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "56972f6dbfd1e3037f5ec32433a340a5396ed074",
 "version": "1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
