class NmkRootConfig:
    PYTHON_PATH = "pythonPath"
    BASE_DIR = "BASEDIR"
    ROOT_DIR = "ROOTDIR"
    CACHE_DIR = "CACHEDIR"
    PROJECT_DIR = "PROJECTDIR"
    PROJECT_FILES = "PROJECTFILES"
    ENV = "ENV"
