
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T21:20:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f763a2beda46fac6c9f037a03b7b90b67b18664e",
 "version": "0.2.39.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
