
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T21:30:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c836475508c24d7e9776a21eb571de7c527b2ee0",
 "version": "2022.10.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
