
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T08:26:32+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f2c736e77551bc9101dbc486004a1ffd46bebc5",
 "version": "0.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
