
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T12:31:01+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8afa2d7a6431e7a951b3c72650dff10cb96afdca",
 "version": "v3.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
