VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('29')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 0
MINOR_VERSION = 20
PATCH_VERSION = 202210291411
version_date = '2022/10/29 14:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
