
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T21:43:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9c223b77490b25d589a94384af63e09df19b440",
 "version": "0.2.39.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
