
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T09:24:44+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "01797b8a1f16b48a8682ce9f021c54ec1212fc8f",
 "version": "0.5.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
