
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T14:49:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "275c9d1aa8bbd422a86cb400d8dbabfcc6bd5093",
 "version": "v1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
