
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-29T11:55:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7316f99557e6dffe5664ab177252446b1376b0a6",
 "version": "v0.0.1-beta.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
