
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T09:54:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d09769e0e3b6b929a337ab8c8c5457b7d1c0d77d",
 "version": "0.1.0a79"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
