
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T18:30:28+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a6685b682aa36eca368e4e5cf64961826061697",
 "version": "v3.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
