
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T09:20:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4933cb3f4a637c4a6dc97ffa72a16bf147c3a120",
 "version": "4.7.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
