
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T16:00:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c996ce890581e4e2ee7588b4fd1fa19c47d1a27d",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
