
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T22:47:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c62ef4ff905d014eeeca5df23dec34d20e7bddd",
 "version": "0.1.1.post0.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
