
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/mitol/hubspot_api:mitol-hubspot_api

from setuptools import setup

setup(**{
    'authors': [
        'MIT Office of Open Learning <mitx-devops@mit.edu>',
    ],
    'classifiers': [
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
    'description': 'Django application for Hubspot API integration',
    'install_requires': (
        'django<4.0,>=2.2.12',
        'factory-boy~=3.2',
        'mitol-django-common~=2.6.0',
        'pytest==6.1.2',
        'setuptools',
    ),
    'license': 'BSD 3-Clause License',
    'name': 'mitol-django-hubspot-api',
    'namespace_packages': (
        'mitol',
    ),
    'package_data': {
        'mitol.hubspot_api': (
            'CHANGELOG.md',
            'README.md',
            'py.typed',
        ),
    },
    'packages': (
        'mitol',
        'mitol.hubspot_api',
        'mitol.hubspot_api.migrations',
        'mitol.hubspot_api.settings',
    ),
    'version': '1.0.0',
    'zip_safe': True,
})
