VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('02')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('28')
MAJOR_VERSION = 0
MINOR_VERSION = 20
PATCH_VERSION = 202211020828
version_date = '2022/11/02 08:28'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
