
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T13:38:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa7ca2f6d7ec3414bcb60f26e3f1eaec6ef372e7",
 "version": "2782"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
