# Generated by Django 3.2.13 on 2022-06-27 19:15

import django.core.serializers.json
from django.db import migrations, models
import funkwhale_api.audio.models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_channel_rss_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='metadata',
            field=models.JSONField(blank=True, default=funkwhale_api.audio.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
    ]
