
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T16:01:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "62b670060e8b862d80bd71b8b71171b01787360d",
 "version": "6.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
