
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T09:54:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c2627a68e9e5d54dee0130fa9fbde37c18f52f7",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
