
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T23:37:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb3eadd3441561d6093f01e4e4fbae850b830cab",
 "version": "1.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
