
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-30T14:54:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9985f4f2d59ce6787c495092285402583e1970c",
 "version": "0.10.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
