
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T15:53:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9084f343d45bdd528fd0c58bcd3c145299e3ed88",
 "version": "1.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
