
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T11:53:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "40bbfedf4fe69c44db9a0fa26a81617a9583f741",
 "version": "v22.12.00a221031"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
