
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T10:02:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f6c25ff2687d9d1deb48a3e7e0a4b546d2ceb4e",
 "version": "2022.11.02"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
