
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T14:32:07-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "93ee966db15ee7656aa937c4a23f5bd6f6bc5e2d",
 "version": "1.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
