SPARK_TO_CLICKHOUSE_TYPES = {
    "string": "String",
    "boolean": "Bool",
    "tinyint": "Int8",
    "smallint": "Int16",
    "int": "Int32",
    "bigint": "Int64",
    "float": "Float32",
    "double": "Float64",
    "date": "Date",
    "timestamp": "DateTime",
    "array<string>": "Array(String)",
    "array<boolean>": "Array(Bool)",
    "array<tinyint>": "Array(Int8)",
    "array<smallint>": "Array(Int16)",
    "array<int>": "Array(Int32)",
    "array<bigint>": "Array(Int64)",
    "array<float>": "Array(Float32)",
    "array<double>": "Array(Float64)",
    "array<date>": "Array(Date)",
    "array<timestamp>": "Array(DateTime)",
}
