
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T19:19:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dbc4c9353d043cc5bd4530154809f8918d571d9",
 "version": "v22.12.00a221103"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
