from google.cloud import bigquery

FIELDS_TMP_BQ = [
            bigquery.SchemaField("brand_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("customer_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("cooler_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("cooler_ref", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("outlet_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("outlet_name", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("outlet_address", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("outlet_devices", "INTEGER", mode="NULLABLE"),
            bigquery.SchemaField("region", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("management_zone", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("channel_desc", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("outlet_class", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("route", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("latitude", "FLOAT", mode="NULLABLE"),
            bigquery.SchemaField("longitude", "FLOAT", mode="NULLABLE"),
            bigquery.SchemaField("gcs", "BOOLEAN", mode="NULLABLE"),
            bigquery.SchemaField("conditions", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("phone_number", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("months_without_sale", "FLOAT", mode="NULLABLE"),
            bigquery.SchemaField("sales_avg_trim", "FLOAT", mode="NULLABLE"),
            bigquery.SchemaField("last_month_sale", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("business_contact", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("channel", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("inserted_at", "TIMESTAMP", mode="NULLABLE"),
            bigquery.SchemaField("period", "TIMESTAMP", mode="NULLABLE"),
            bigquery.SchemaField("model_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("mac", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("controller_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("console", "BOOLEAN", mode="NULLABLE"),
            bigquery.SchemaField("sales", "BOOLEAN", mode="NULLABLE"),
            bigquery.SchemaField("status_kof", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("installed_date", "TIMESTAMP", mode="NULLABLE")
        ]