
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-26T14:25:31+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "063338d21350336aa2a5d599c94ba72543f9af76",
 "version": "v0.2b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
