# Generated by Django 3.2.13 on 2022-06-27 19:15

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0005_auto_20200803_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='config',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
