# Generated by Django 3.2.10 on 2022-01-21 11:56

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0005_auto_20200803_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiosession',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
