
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T13:09:09+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "66913123994b4f364cad9b9b2af3215508091a15",
 "version": "v3.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
