
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T14:40:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d7bd9325200aefd49106422aa8795751383b34e",
 "version": "0.1.3.post0.dev102"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
