
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T10:35:44+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "37d636552d91ea6d62cfd41a9dd5adacc4f2a483",
 "version": "v3.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
