
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T09:07:07+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "483d65e3eab4a127328449fd23284bfb9f55def7",
 "version": "0.1.1-rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
