
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-30T16:24:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b4affb8c36ac32209958df94f43f5c0174f4c87",
 "version": "1.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
