
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T09:50:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "56570396887ac394091eb989fd0fd41ae2946ede",
 "version": "1.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
