
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T15:18:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "40598d1aca6b83763fdd7881a8a35ce06fe7f5aa",
 "version": "v0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
