# Generated by Django 3.2.13 on 2022-07-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0006_alter_radio_config'),
        ('radios', '0006_radiosession_config'),
    ]

    operations = [
    ]
