from .resources import (
    CitationAffector,
    CodeUnit,
    DocUnit,
    EventCitation,
    EventStatute,
    Identifier,
    Node,
    Page,
    StatuteAffector,
    StatuteUnit,
    generic_content,
    generic_email,
    generic_mp,
)
