
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T21:10:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb8eed6aa0d0627cc46ffc9986c6a5eca61be323",
 "version": "6.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
