
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T06:18:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ccab59edbd90e0ad0e1bdf5d09bea3847e481403",
 "version": "v1.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
