
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T18:29:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "48bdc61220ea6bf881b99afe8e438d16f950a299",
 "version": "7.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
