# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/h3-landmarks',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/h3-landmarks',
                'lib_path': 'h3_landmarks'},
  'syms': { 'h3_landmarks.core': {'h3_landmarks.core.foo': ('core.html#foo', 'h3_landmarks/core.py')},
            'h3_landmarks.h3_landmarks': { 'h3_landmarks.h3_landmarks.foo': ('hlandmarks.html#foo', 'h3_landmarks/h3_landmarks.py'),
                                           'h3_landmarks.h3_landmarks.say_hello': ( 'hlandmarks.html#say_hello',
                                                                                    'h3_landmarks/h3_landmarks.py')}}}