
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-29T09:30:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ee45f263f7e28a3cf2bb57d349ee906998c5f49",
 "version": "1.9.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
