
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T07:59:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "053eaa4c13b0b4a521022d8ef0b450dc528a72d0",
 "version": "7.18.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
