
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-30T23:01:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea721e4a833a63825bf6aa7ba92f30079931e8b8",
 "version": "4.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
