
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T08:12:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "75ec50dbe4964d83cfd4820e97127e260da63fc8",
 "version": "0.13.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
