
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T14:10:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d813c3a3b8254f2327df0a60be9c77031531602",
 "version": "0.2.40.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
