
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T17:53:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d86f6cb67f7850ee71fae45cd497fe7b673a65b7",
 "version": "0.1.1.post0.dev29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
