
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T15:59:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c19ea0efe92dc7be21b0c87693df923cb4cc58da",
 "version": "0.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
