
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-11-01T17:22:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a0ffca8d9fb9caf026b6e0684c135d46bed9bf9",
 "version": "6.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
