
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T22:22:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e16f79852db7beb9ec65abe48362e081c36895d2",
 "version": "0.0.127"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
