
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T22:36:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "699e50e7b6b166eaa540eddf88c007429726247b",
 "version": "2022.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
