
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T16:37:30-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbf6be89f826a0a30d2428f381cc9ad7a49e490f",
 "version": "6.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
