
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-31T17:07:33-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "8117b4f00f1167d3d186694fcf8c565db8a66295",
 "version": "1.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
