VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('01')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 0
MINOR_VERSION = 20
PATCH_VERSION = 202211010911
version_date = '2022/11/01 09:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
