
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T11:40:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0f867a8a6ff80007d671266e969cf586bc95fa5",
 "version": "0.7.1.post.dev796"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
