
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T15:56:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c745790e1420885ac8fcf544d11a82a1227e0fd1",
 "version": "v1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
