PROVIDER_DIGITAL_OCEAN = "digitalocean"

AVAILABLE_PROVIDERS = (PROVIDER_DIGITAL_OCEAN,)

TYPE_RECORD_A = "A"
TYPE_RECORD_AAAA = "AAAA"
TYPE_RECORD_CAA = "CAA"
TYPE_RECORD_CNAME = "CNAME"
TYPE_RECORD_MX = "MX"
TYPE_RECORD_NS = "NS"
TYPE_RECORD_SOA = "SOA"
TYPE_RECORD_SRV = "SRV"
TYPE_RECORD_TXT = "TXT"

VALID_TYPES_RECORDS = (
    TYPE_RECORD_A,
    TYPE_RECORD_AAAA,
    TYPE_RECORD_CAA,
    TYPE_RECORD_CNAME,
    TYPE_RECORD_MX,
    TYPE_RECORD_NS,
    TYPE_RECORD_SOA,
    TYPE_RECORD_SRV,
    TYPE_RECORD_TXT,
)

STATUS_CODE_200_OK = 200
STATUS_CODE_201_CREATED = 201
STATUS_CODE_204_NO_CONTENT = 204
STATUS_CODE_401_UNAUTHORIZED = 401
STATUS_CODE_404_NOT_FOUND = 404
STATUS_CODE_422_UNPROCESSABLE_ENTITY = 422
STATUS_CODE_429_TO_MANY_REQUESTS = 429
STATUS_CODE_500_SERVER_ERROR = 500


DEFAULT_CLOUDYNS_ERROR_CODE = "DEFAULT_CLOUDYNS_ERROR_MESSAGE"
DEFAULT_CLOUDYNS_ERROR_MESSAGE = "DEFAULT_CLOUDYNS_ERROR_MESSAGE"

DEFAULT_API_CONNECTION_ERROR_CODE = "DEFAULT_API_CONNECTION_ERROR_CODE"
DEFAULT_API_CONNECTION_ERROR_MESSAGE = "DEFAULT_API_CONNECTION_ERROR_MESSAGE"
