# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .migration import *
from .migrations import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gomigrate",
  "mod": "index",
  "fqn": "pulumi_gomigrate",
  "classes": {
   "gomigrate:index:Migration": "Migration",
   "gomigrate:index:Migrations": "Migrations"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gomigrate",
  "token": "pulumi:providers:gomigrate",
  "fqn": "pulumi_gomigrate",
  "class": "Provider"
 }
]
"""
)
