
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T22:49:08-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ca59eb9ae5bbaba931dd5f739e2d971e3e7e5a1",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
