
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-30T02:54:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b11d184b83bf9f0094a0d279194e8f446df399d",
 "version": "1.1.dev2244"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
