
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-01T18:24:31+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "7da150b7405d6be513e0c0a76fa6ab2f22e2b26d",
 "version": "v3.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
