
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-28T16:31:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a3ec8dbcf2c3ae317b30fa21079f154062f061f",
 "version": "2.8.7.dev20221102"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
