
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/mitol/digitalcredentials:mitol-django-digital-credentials

from setuptools import setup

setup(**{
    'authors': [
        'MIT Office of Open Learning <mitx-devops@mit.edu>',
    ],
    'classifiers': [
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
    'description': 'Django application to support digital credentials',
    'install_requires': (
        'django-oauth-toolkit>=1.3.3',
        'django<4.0,>=2.2.12',
        'djangorestframework>=3.0.0',
        'factory-boy~=3.2',
        'mitol-django-common~=2.6.0',
        'requests>=2.20.0',
    ),
    'license': 'BSD 3-Clause License',
    'name': 'mitol-django-digital-credentials',
    'namespace_packages': (
        'mitol',
    ),
    'package_data': {
        'mitol.digitalcredentials': (
            'CHANGELOG.md',
            'README.md',
            'py.typed',
        ),
    },
    'packages': (
        'mitol',
        'mitol.digitalcredentials',
        'mitol.digitalcredentials.migrations',
    ),
    'version': '3.2.1',
    'zip_safe': True,
})
