
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-11-01T13:29:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "04fa756d9ccafcdbe71900d088bd5d00bfdabe35",
 "version": "5.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
