
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-27T11:04:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5155de4abdcbd686d37a68a7f47f0039648626a4",
 "version": "1.95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
