# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hdr-random',
                'doc_host': 'https://chrphb.github.io',
                'git_url': 'https://github.com/chrphb/hdr-random',
                'lib_path': 'hdr_random'},
  'syms': { 'hdr_random.core': { 'hdr_random.core.HDRandom': ('core.html#hdrandom', 'hdr_random/core.py'),
                                 'hdr_random.core.HDRandom.__init__': ('core.html#hdrandom.__init__', 'hdr_random/core.py'),
                                 'hdr_random.core.HDRandom.__str__': ('core.html#hdrandom.__str__', 'hdr_random/core.py'),
                                 'hdr_random.core.HDRandom.generate': ('core.html#hdrandom.generate', 'hdr_random/core.py')}}}