# Generated by Django 3.2.13 on 2022-06-27 19:15

import django.core.serializers.json
from django.db import migrations, models
import funkwhale_api.federation.models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0026_public_key_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='payload',
            field=models.JSONField(blank=True, default=funkwhale_api.federation.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='actor',
            name='manually_approves_followers',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='nodeinfo',
            field=models.JSONField(blank=True, default=funkwhale_api.federation.models.empty_dict, max_length=50000),
        ),
        migrations.AlterField(
            model_name='fetch',
            name='detail',
            field=models.JSONField(blank=True, default=funkwhale_api.federation.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='follow',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='libraryfollow',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='librarytrack',
            name='metadata',
            field=models.JSONField(blank=True, default=funkwhale_api.federation.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=10000),
        ),
    ]
