# Generated by Django 3.2.16 on 2022-10-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0027_auto_20220627_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='last_successful_contact',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='reachable',
            field=models.BooleanField(default=True),
        ),
    ]
