
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T10:23:15-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "855dc5494f7eca86066d75f9d5b68aa78efb551e",
 "version": "1.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
