# Generated by Django 3.2.13 on 2022-06-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210703_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=None, max_length=50000, null=True),
        ),
    ]
