
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/mitol/oauth_toolkit_extensions:mitol-django-oauth-toolkit-extensions

from setuptools import setup

setup(**{
    'authors': [
        'MIT Office of Open Learning <mitx-devops@mit.edu>',
    ],
    'classifiers': [
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
    'description': 'MIT Open Learning django app extensions for oauth toolkit',
    'install_requires': (
        'django-oauth-toolkit>=1.3.3',
        'django<4.0,>=2.2.12',
        'factory-boy~=3.2',
        'mitol-django-common~=2.6.0',
        'pytz>=2020.4',
        'requests>=2.20.0',
    ),
    'license': 'BSD 3-Clause License',
    'name': 'mitol-django-oauth-toolkit-extensions',
    'namespace_packages': (
        'mitol',
    ),
    'package_data': {
        'mitol.oauth_toolkit_extensions': (
            'CHANGELOG.md',
            'README.md',
            'py.typed',
        ),
    },
    'packages': (
        'mitol',
        'mitol.oauth_toolkit_extensions',
        'mitol.oauth_toolkit_extensions.migrations',
    ),
    'version': '1.2.1',
    'zip_safe': True,
})
