
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-02T12:53:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2814a9c65a80348da1f2642ed1a80cdf6c5f0bb",
 "version": "0.2.40.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
